name: Concatenate Sequences

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  concatenate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install biopython

    - name: Concatenate sequences
      run: |
        python concat_sequences.py -f fasta -o concatenated.fasta --fill-missing --sequence-length 100 data/input1.fasta data/input2.fasta
      env:
        INPUT_FILES: data/input1.fasta data/input2.fasta
        OUTPUT_FILE: concatenated.fasta
